### PR TITLE
Add Compatibility with Joomla! 3.5

### PR DESCRIPTION
**Pull request by machadoug**

### CODE REVIEW

**Comment by elkuku** [comment]
Thanks!
I'll try to publish a new version soonish :wink:

**Comment by Bodge-IT** [comment]
need some tests?

**Comment by elkuku** [comment]
Yes please :)

Gary Barclay <notifications@github.com> schrieb am Mi., 23. Mär. 2016 12:46:

**Comment by Bodge-IT** [comment]
OK still have the issue with being unable to create the API list #38 due to missing files described by @HermanPeeran.
Not sure the thing is ready to work in 3.5 yet.

Certainly no errors in the interface or install process

**Pull request merged**
